version: "3.3"
services:
  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=lismove@externals
      - POSTGRES_DB=lismove
      - POSTGRES_PASSWORD=lismovers_00