package net.nextome.lismove.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class PartialDto {
	private Integer type;
	private Double latitude;
	private Double longitude;
	private Double altitude;
	private BigDecimal sensorDistance;
	@ApiModelProperty("Generated by server")
	private BigDecimal gpsDistance;
	@ApiModelProperty("Generated by server")
	private BigDecimal gmapsDistance;
	private Double deltaRevs;
	private Boolean urban;
	@ApiModelProperty("Generated by server")
	private Boolean valid;
	@ApiModelProperty("Generated by server")
	private Integer status;
	private Long timestamp;
	private Long rawData_wheel;
	private Long rawData_ts;
	private String extra;

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Double getLatitude() {
		return latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public Double getLongitude() {
		return longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public void setCoordinates(Double latitude, Double longitude) {
		this.latitude = latitude;
		this.longitude = longitude;
	}

	public Double getAltitude() {
		return altitude;
	}

	public void setAltitude(Double altitude) {
		this.altitude = altitude;
	}

	public BigDecimal getSensorDistance() {
		return sensorDistance;
	}

	public void setSensorDistance(BigDecimal sensorDistance) {
		this.sensorDistance = sensorDistance;
	}

	public Double getDeltaRevs() {
		return deltaRevs;
	}

	public void setDeltaRevs(Double deltaRevs) {
		this.deltaRevs = deltaRevs;
	}

	public Boolean getUrban() {
		return urban;
	}

	public void setUrban(Boolean urban) {
		this.urban = urban;
	}

	public Boolean getValid() {
		return valid;
	}

	public void setValid(Boolean valid) {
		this.valid = valid;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Long getTimestamp() {
		return timestamp;
	}

	public void setTimestamp(Long timestamp) {
		this.timestamp = timestamp;
	}

	public BigDecimal getGpsDistance() {
		return gpsDistance;
	}

	public void setGpsDistance(BigDecimal gpsDistance) {
		this.gpsDistance = gpsDistance;
	}

	public BigDecimal getGmapsDistance() {
		return gmapsDistance;
	}

	public void setGmapsDistance(BigDecimal gmapsDistance) {
		this.gmapsDistance = gmapsDistance;
	}

	public Long getRawData_wheel() {
		return rawData_wheel;
	}

	public void setRawData_wheel(Long rawData_wheel) {
		this.rawData_wheel = rawData_wheel;
	}

	public Long getRawData_ts() {
		return rawData_ts;
	}

	public void setRawData_ts(Long rawData_ts) {
		this.rawData_ts = rawData_ts;
	}

	public String getExtra() {
		return extra;
	}

	public void setExtra(String extra) {
		this.extra = extra;
	}
}
