package net.nextome.lismove.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.List;
import java.util.UUID;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class SessionDto {

	@ApiModelProperty("Generated by server")
	private UUID id;
	@ApiModelProperty("Generated by server")
	private Integer type;
	@ApiModelProperty("Generated by server")
	private Boolean valid;
	@ApiModelProperty("Generated by server")
	private Integer status;
	@ApiModelProperty("Generated by server")
	private Boolean certificated;
	private Long startTime;
	private Long endTime;
	@ApiModelProperty("Generated by server")
	private Integer duration;
	private BigDecimal gyroDistance;
	private BigDecimal gpsOnlyDistance;
	@ApiModelProperty("Generated by server")
	private BigDecimal gpsDistance;
	@ApiModelProperty("Generated by server")
	private BigDecimal gmapsDistance;
	@Deprecated
	@ApiModelProperty("Deprecated")
	private BigDecimal urbanKm;
	@Deprecated
	@ApiModelProperty("Deprecated")
	private Integer initiativePoints;
	@Deprecated
	@ApiModelProperty("Deprecated")
	private Double multiplier;
	private BigDecimal nationalKm;
	private Integer nationalPoints;
	@Deprecated
	@ApiModelProperty("Deprecated")
	private BigDecimal totalKm;
	@ApiModelProperty("Generated by server")
	private Boolean isHomeWorkPath;
	@ApiModelProperty("Generated by server")
	private BigDecimal euro;
	private String description;
	private Double startBattery;
	private Double endBattery;
	private String uid;
	@ApiModelProperty("Generated by server")
	private List<String> polyline;
	private List<String> rawPolyline;
	private List<String> gmapsPolyline;
	private Integer phoneStartBattery;
	private Integer phoneEndBattery;
	@ApiModelProperty("Generated by server")
	private Double co2;
	private String firmware;
	//HomeWork path
	@ApiModelProperty("Generated by server")
	private Long homeAddress;
	@ApiModelProperty("Generated by server")
	private Long workAddress;
	//Verifica
	private Boolean verificationRequired;
	private String verificationRequiredNote;

	private List<PartialDto> partials;
	private List<SessionPointDto> sessionPoints;

	public UUID getId() {
		return id;
	}

	public void setId(UUID id) {
		this.id = id;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Boolean getValid() {
		return valid;
	}

	public void setValid(Boolean valid) {
		this.valid = valid;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Boolean getCertificated() {
		return certificated;
	}

	public void setCertificated(Boolean certificated) {
		this.certificated = certificated;
	}

	public Long getStartTime() {
		return startTime;
	}

	public void setStartTime(Long startTime) {
		this.startTime = startTime;
	}

	public Long getEndTime() {
		return endTime;
	}

	public void setEndTime(Long endTime) {
		this.endTime = endTime;
	}

	public Integer getDuration() {
		return duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	public BigDecimal getGyroDistance() {
		return gyroDistance;
	}

	public void setGyroDistance(BigDecimal gyroDistance) {
		this.gyroDistance = gyroDistance;
	}

	public BigDecimal getGpsDistance() {
		return gpsDistance;
	}

	public void setGpsDistance(BigDecimal gpsDistance) {
		this.gpsDistance = gpsDistance;
	}

	public BigDecimal getGpsOnlyDistance() {
		return gpsOnlyDistance;
	}

	public void setGpsOnlyDistance(BigDecimal gpsOnlyDistance) {
		this.gpsOnlyDistance = gpsOnlyDistance;
	}

	public BigDecimal getGmapsDistance() {
		return gmapsDistance;
	}

	public void setGmapsDistance(BigDecimal gmapsDistance) {
		this.gmapsDistance = gmapsDistance;
	}

	public BigDecimal getUrbanKm() {
		return urbanKm;
	}

	public void setUrbanKm(BigDecimal urbanKm) {
		this.urbanKm = urbanKm;
	}

	public Integer getInitiativePoints() {
		return initiativePoints;
	}

	public void setInitiativePoints(Integer initiativePoints) {
		this.initiativePoints = initiativePoints;
	}

	public BigDecimal getNationalKm() {
		return nationalKm;
	}

	public void setNationalKm(BigDecimal nationalKm) {
		this.nationalKm = nationalKm;
	}

	public Integer getNationalPoints() {
		return nationalPoints;
	}

	public void setNationalPoints(Integer nationalPoints) {
		this.nationalPoints = nationalPoints;
	}

	public BigDecimal getTotalKm() {
		return totalKm;
	}

	public void setTotalKm(BigDecimal totalKm) {
		this.totalKm = totalKm;
	}

	public Boolean getHomeWorkPath() {
		return isHomeWorkPath;
	}

	public void setHomeWorkPath(Boolean homeWorkPath) {
		isHomeWorkPath = homeWorkPath;
	}

	public BigDecimal getEuro() {
		return euro;
	}

	public void setEuro(BigDecimal euro) {
		this.euro = euro;
	}

	public Double getMultiplier() {
		return multiplier;
	}

	public void setMultiplier(Double multiplier) {
		this.multiplier = multiplier;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Double getStartBattery() {
		return startBattery;
	}

	public void setStartBattery(Double startBattery) {
		this.startBattery = startBattery;
	}

	public Double getEndBattery() {
		return endBattery;
	}

	public void setEndBattery(Double endBattery) {
		this.endBattery = endBattery;
	}

	public List<PartialDto> getPartials() {
		return partials;
	}

	public void setPartials(List<PartialDto> partials) {
		this.partials = partials;
	}

	public String getUid() {
		return uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	public List<String> getPolyline() {
		return polyline;
	}

	public void setPolyline(List<String> polyline) {
		this.polyline = polyline;
	}

	public List<String> getRawPolyline() {
		return rawPolyline;
	}

	public void setRawPolyline(List<String> rawPolyline) {
		this.rawPolyline = rawPolyline;
	}

	public List<String> getGmapsPolyline() {
		return gmapsPolyline;
	}

	public void setGmapsPolyline(List<String> gmapsPolyline) {
		this.gmapsPolyline = gmapsPolyline;
	}

	public Integer getPhoneStartBattery() {
		return phoneStartBattery;
	}

	public void setPhoneStartBattery(Integer phoneStartBattery) {
		this.phoneStartBattery = phoneStartBattery;
	}

	public Integer getPhoneEndBattery() {
		return phoneEndBattery;
	}

	public void setPhoneEndBattery(Integer phoneEndBattery) {
		this.phoneEndBattery = phoneEndBattery;
	}

	public Double getCo2() {
		return co2;
	}

	public void setCo2(Double co2) {
		this.co2 = co2;
	}

	public List<SessionPointDto> getSessionPoints() {
		return sessionPoints;
	}

	public void setSessionPoints(List<SessionPointDto> sessionPoints) {
		this.sessionPoints = sessionPoints;
	}

	public String getFirmware() {
		return firmware;
	}

	public void setFirmware(String firmware) {
		this.firmware = firmware;
	}

	public Long getHomeAddress() {
		return homeAddress;
	}

	public void setHomeAddress(Long homeAddress) {
		this.homeAddress = homeAddress;
	}

	public Long getWorkAddress() {
		return workAddress;
	}

	public void setWorkAddress(Long workAddress) {
		this.workAddress = workAddress;
	}

	public Boolean getVerificationRequired() {
		return verificationRequired;
	}

	public void setVerificationRequired(Boolean verificationRequired) {
		this.verificationRequired = verificationRequired;
	}

	public String getVerificationRequiredNote() {
		return verificationRequiredNote;
	}

	public void setVerificationRequiredNote(String verificationRequiredNote) {
		this.verificationRequiredNote = verificationRequiredNote;
	}
}
